steps:
  - name: node:16
    entrypoint: yarn
    args:
      - 'install'
  - name: node:16
    entrypoint: yarn
    args:
      - 'build'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - app
      - deploy
      - '--project=nuxt-sample-353603'
timeout: 1200s
